version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: perago-postgres
    environment:
      POSTGRES_USER: org_user
      POSTGRES_PASSWORD: user_pwd123
      POSTGRES_DB: organization_structure
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:16
    environment:
      POSTGRES_USER: org_user
      POSTGRES_PASSWORD: user_pwd123
      POSTGRES_DB: organization_structure_test
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
