POST http://localhost:3000/employees
Content-Type: application/json

{
  "fullName": "Abebe Tesfu",
  "email": "abebe123@perago.com",
  "phone": "0987334423",
  "gender": "M",
  "birthDate": "2000-03-05T11:51:06.753Z",
  "hireDate": "2020-07-05T11:51:06.753Z",
  "roleId": "d99deb28-bd68-4072-a6fc-006d3bc8438d",
  "photo": "https://robohash.org/hicveldicta.png?size=50x50&set=set1"
}

###
GET http://localhost:3000/employees/
###
GET http://localhost:3000/employees/73540668-9a17-4f2f-ad05-578d8e3d8b34
###
PATCH http://localhost:3000/employees/c30dbd20-3c46-4824-8d29-35320c297a11
Content-Type: application/json

{
  "fullName": "Appo Keppa"
}


###
DELETE http://localhost:3000/employees/73540668-9a17-4f2f-ad05-578d8e3d8b34