POST http://localhost:3000/employees
Content-Type: application/json

{
  "fullName": "Abebe Tesfu",
  "email": "abebe123@perago.com",
  "phone": "0987334423",
  "gender": "M",
  "birthDate": "2000-03-05T11:51:06.753Z",
  "hireDate": "2020-07-05T11:51:06.753Z",
  "roleId": "0764a223-5494-4f41-b204-81a148fae0db",
  "photo": "https://robohash.org/hicveldicta.png?size=50x50&set=set1"
}

###
GET http://localhost:3000/employees/
###
GET http://localhost:3000/employees/8146bb8e-9a19-4165-b5dd-eaa045b1a443

###
PATCH http://localhost:3000/employees/8146bb8e-9a19-4165-b5dd-eaa045b1a443
Content-Type: application/json

{
  "fullName": "Appo Keppa"
}


###
DELETE http://localhost:3000/employees/c76fd9c9-fd43-4c22-82b2-916ce20a69c5