POST http://localhost:3000/employees
Content-Type: application/json

{
  "fullName": "Abebe Tesfu",
  "email": "abebe123@perago.com",
  "phone": "0987334423",
  "gender": "M",
  "birthDate": "2000-03-05T11:51:06.753Z",
  "hireDate": "2020-07-05T11:51:06.753Z",
  "roleId": "d1f323e2-a611-4f49-8297-4f9911d4f266",
  "photo": "https://robohash.org/hicveldicta.png?size=50x50&set=set1"
}

###
GET http://localhost:3000/employees/
###
GET http://localhost:3000/employees/3aa1e133-ac30-463c-b2a9-3d1b1ba47733

###
PATCH http://localhost:3000/employees/3aa1e133-ac30-463c-b2a9-3d1b1ba47733
Content-Type: application/json

{
  "photo": "https://robohash.org/hicveldicta.png?size=50x50&set=set1"
}


###
DELETE http://localhost:3000/employees/bc248988-2b89-426b-a1cc-616575d23fa1