# Get heirarchy of roles
GET http://localhost:3000/roles


### Get list of roles
GET http://localhost:3000/roles?flat=true&limit=2&page=2

###
GET http://localhost:3000/roles/

###
GET http://localhost:3000/roles/878576f6-4dfb-42d7-b57a-c4285c3263e3

### create new role
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "UX designer",
  "description": "A UX designer is designs the graphical user interface of an app, website, or device that a human interacts with",
  "parentId": "b8ab33ab-29bf-4271-ad5b-3689733c74fd"
}

###
# create CTO && add as parent of Project Manager
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "CTO",
  "parentId": 1
}
###
PATCH http://localhost:3000/roles/6
Content-Type: application/json

{
  "parentId": 8
}

###
# update projects
PATCH http://localhost:3000/roles/12
Content-Type: application/json

{
  "description": "I break the product for the developers to fix"
}

###
# delete a role with no children
DELETE http://localhost:3000/roles/7fad1be0-5a11-4312-bf88-71420a2393bb

### delete a role with its children
DELETE http://localhost:3000/roles/ee612665-819b-47a8-b087-a24a44d4c932
