# Get heirarchy of roles
GET http://localhost:3000/roles


### Get list of roles
GET http://localhost:3000/roles?flat=true

###
GET http://localhost:3000/roles?depth=2

###
GET http://localhost:3000/roles/670abc90-8f13-41cb-860f-0b5dcfeb514e

### create new role
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "UX developer",
  "parentId": "ee606125-ce40-4164-80eb-48b27bd811e0"
}

###
# create CTO && add as parent of Project Manager
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "CTO",
  "parentId": 1
}
### 878576f6-4dfb-42d7-b57a-c4285c3263e3
PATCH http://localhost:3000/roles/b45a99c7-8935-4255-b7b9-3abe94fcd224
Content-Type: application/json

{
  "parentId": "878576f6-4dfb-42d7-b57a-c4285c3263e3"
}

###
# update projects
PATCH http://localhost:3000/roles/12
Content-Type: application/json

{
  "description": "I break the product for the developers to fix"
}

###
# delete a role with no children
DELETE http://localhost:3000/roles/7fad1be0-5a11-4312-bf88-71420a2393bb

### delete a role with its children
DELETE http://localhost:3000/roles/817e1d92-c5ea-418a-b31a-a44020c9e3b9
Content-Type: application/json

{
"parentId": "b45a99c7-8935-4255-b7b9-3abe94fcd224"  
}
###
GET http://localhost:3000/roles/4452a3e4-09a1-4133-8d13-e9f3712d83c2/employees?limit=3&page=3
###
GET http://localhost:3000/roles/4452a3e4-09a1-4133-8d13-e9f3712d83c2/except_descendants
