# Get all roles
GET http://localhost:3000/roles

###
GET http://localhost:3000/roles/5

###
# create new role
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "CTO",
  "description": "Chief Technology Officer(CTO) manages the physical and personnel technology infrastructure including technology deployment, network and system management, integration testing, and developing technical operations personnel",
  "parentId": 1
}

###
# create CTO && add as parent of Projecct Manager
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "CTO",
  "parentId": 1
}
###
PATCH http://localhost:3000/roles/6
Content-Type: application/json

{
  "parentId": 8
}

###
# update projects
PATCH http://localhost:3000/roles/12
Content-Type: application/json

{
  "description": "I break the product for the developers to fix"
}

###
# delete a role along with its children
DELETE http://localhost:3000/roles/2
